# Generated by Django 3.2.13 on 2022-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FirstName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("is_male", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LastName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                (
                    "matching_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("N", "Neutral")],
                        default="N",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
